apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat
  labels:
    app: tomcat  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat  
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: gcr.io/stoked-genius-302113/tomcatapp:v1
        name: tomcat
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcr-json-key 

---
    
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat  
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
