apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat-ns
  labels:
    app: tomcat  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat  
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: gcr.io/stoked-genius-302113/tomcatapp:v1.35
        name: tomcat
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcr-json-key 
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat-ns  
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-hpa
  namespace: tomcat-ns  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 256Mi        
status:
  observedGeneration: 1
  currentReplicas: 2
  desiredReplicas: 2
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
  - type: Resource
    resource:
      name: memory
      current:
        averageUtilization: 0
        averageValue: 0