apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat  
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: gcr.io/stoked-genius-302113/tomcatapp:v1
        name: tomcatapp
        ports:
        - containerPort: 8080       

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat  
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
